# Jekyll configuration
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

locale: "en-US"
title: "SQA Contractor"
description: "Professional Software Quality Assurance Services"
baseurl: ""
url: ""

# Build settings
markdown: kramdown

# Google Analytics ID placeholder
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-XXXXXXXXX-X"
    anonymize_ip: true
